name: TwGiftTopup
version: ${project.version}
main: me.mcch.twgifttopup.TwGiftTopup
description: a simple plugin to topup with wallet
website: https://github.com/MinecraftChannel/twgifttopup
authors: [_StarChaser, Maythiwat]
commands:
  twgifttopup:
    aliases: [tgt, twtopup]
    description: TwGiftTopup command