name: TwGiftTopup
version: ${project.version}
main: me.mcch.TwGiftTopup
description: a simple plugin to topup with wallet
commands:
  twgifttopup:
    aliases: [tgt, twtopup]
    description: TwGiftTopup command